filter:
  enabled: true
  block_private_addresses: false
  files:
    - "./bench/adblockdns.txt"

inbounds:
  - type: socks5
    listen: "127.0.0.1:1081"
  - type: socks5
    listen: "unix:///tmp/proxylb_bench.sock"

backends:
  - type: socks5
    address: "unix:///tmp/mock_socks5.sock"
    name: "uds-socks5-backend"
    pool_size: 10
    force_healthy: true

  - type: direct
    name: "direct-out"
    force_healthy: true

failover_order:
  - "uds-socks5-backend"

health_check:
  interval_secs: 10
  timeout_secs: 5
  check_target: "http://www.gstatic.com/generate_204"



# cpu_affinity:
#   worker_cores: [1]
#   ancillary_cores: [2]

# advanced:
#   zero_copy: true
